Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------


source_color='blue'
#gnd1 = d.add(e.GND,color=source_color)
#d.add(e.LINE, d='up', l=1)
#d.add(e.SOURCE_V, label='$V_{B}$',color=source_color)
VB = d.add(e.DOT_OPEN, label='$V_{B}$')
# d += (iC := e.LINE().right() )
# d.labelI(L1, '$i_g$', top=False)


#---
#transistor
d.add(e.LINE, d='right', xy=RB.end, l=1)
bjt = d.add(e.BJT_NPN_C, d='right')
#----
# #voltage divider
d.add(e.LINE, d='up', xy=bjt.collector, label='$R_C$')
Vcc = d.add(e.DOT_OPEN, label='$V_{C}$')
# RE = d.add(e.RES, d='down', xy=bjt.emitter, label='$R_E$')
# gnd = d.add(e.GNDd)
#---
d.draw()
# d.save(os.path.join(figure_path,'transistor_basic.pdf'))

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-9-0f96289b396d>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;31m#d.add(e.LINE, d='up', l=1)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;31m#d.add(e.SOURCE_V, label='$V_{B}$',color=source_color)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0mVB[0m [0;34m=[0m [0md[0m[0;34m.[0m[0madd[0m[0;34m([0m[0me[0m[0;34m.[0m[0mDOT_OPEN[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34m'$V_{B}$'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0;31m# d += (iC := e.LINE().right() )[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;31m# d.labelI(L1, '$i_g$', top=False)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'd' is not defined
NameError: name 'd' is not defined

