Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
t = np.linspace(0,100e-3,1e5) # vetor de tempo
f1,f2= 20,1e3 # frequencia e fase
v01,v02 = 1,1 # amplitudes
#----
v1 = v01*np.cos(2*np.pi*f1*t) # sinal v1(t)
v2 = v02*np.cos(2*np.pi*f2*t) # sinal v2(t)
v = v1+v2 # soma dos dois sinais
#----
print('f1 = {} Hz'.format(f1))
print('f2 = {} Hz'.format(f2))
print('f0 = (f1+f2)/2 = {} Hz'.format(0.5*(f1+f2)))
print('Œ¥f = (f1-f2) = {} Hz'.format(np.abs(f1-f2)))
#---- Calculando FFT
freq,Y = fft540(t,v)

### gr√°fico com 4 eixos###
fig, ax = plt.subplots(2, 2,figsize=[10,7])
#tempo
ax[0,0].plot(1e3*t,v)
ax[0,0].set_xlabel('Tempo (ms)')
ax[0,0].set_ylabel('Amplitude (V)')
#tempo com zoom
ax[1,0].plot(1e3*t,v)
ax[1,0].set_xlabel('Tempo (ms)')
ax[1,0].set_ylabel('Amplitude (V)')
ax[1,0].set_xlim([20,25])
ax[1,0].grid(True)
#fft linear - frequencias negativas e positivas
ax[0,1].plot(freq*1e-3, np.abs(Y),'r*-') # plotting the spectrum
ax[0,1].set_xlabel('Freq (kHz)')
ax[0,1].set_ylabel('|Y(freq)|')
ax[0,1].set_xlim([-5,5])
ax[0,1].grid(True)
#fft semilog - frequencias positivas
mask = range(0,int(len(t)/2)) # m√°scara para pegar apenas metade do vetor
freq_pos = freq[mask]
Y_pos = Y[mask]
ax[1,1].semilogx(freq_pos*1e-3, np.abs(Y_pos),'r') # plotting the spectrum
ax[1,1].set_xlabel('Freq (kHz)')
ax[1,1].set_ylabel('|Y(freq)|')
ax[1,1].set_xlim([1e-3,1e3])
ax[1,1].grid(True)
#ajustar e mostrar
plt.tight_layout()
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-8-2c662f5d0cd3>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mt[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mlinspace[0m[0;34m([0m[0;36m0[0m[0;34m,[0m[0;36m100e-3[0m[0;34m,[0m[0;36m1e5[0m[0;34m)[0m [0;31m# vetor de tempo[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mf1[0m[0;34m,[0m[0mf2[0m[0;34m=[0m [0;36m20[0m[0;34m,[0m[0;36m1e3[0m [0;31m# frequencia e fase[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mv01[0m[0;34m,[0m[0mv02[0m [0;34m=[0m [0;36m1[0m[0;34m,[0m[0;36m1[0m [0;31m# amplitudes[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;31m#----[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mv1[0m [0;34m=[0m [0mv01[0m[0;34m*[0m[0mnp[0m[0;34m.[0m[0mcos[0m[0;34m([0m[0;36m2[0m[0;34m*[0m[0mnp[0m[0;34m.[0m[0mpi[0m[0;34m*[0m[0mf1[0m[0;34m*[0m[0mt[0m[0;34m)[0m [0;31m# sinal v1(t)[0m[0;34m[0m[0;34m[0m[0m

[0;32m<__array_function__ internals>[0m in [0;36mlinspace[0;34m(*args, **kwargs)[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/function_base.py[0m in [0;36mlinspace[0;34m(start, stop, num, endpoint, retstep, dtype, axis)[0m
[1;32m    111[0m [0;34m[0m[0m
[1;32m    112[0m     """
[0;32m--> 113[0;31m     [0mnum[0m [0;34m=[0m [0moperator[0m[0;34m.[0m[0mindex[0m[0;34m([0m[0mnum[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    114[0m     [0;32mif[0m [0mnum[0m [0;34m<[0m [0;36m0[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    115[0m         [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34m"Number of samples, %s, must be non-negative."[0m [0;34m%[0m [0mnum[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: 'float' object cannot be interpreted as an integer
TypeError: 'float' object cannot be interpreted as an integer

